configName: mclv2_sam_c21_pim
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAMC21J18A
projectName: ''
settings:
  PackageFilter: bsp;core;csp;motor_control;x2c;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMC21_DFP\3.5.83\samc21\atdf\ATSAMC21J18A.atdf
