format_version: v1.0
type: UniqueComponent
attributes: {id: adc0}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: ADC_CONV_TRIGGER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: HW Event Trigger}
  - type: KeyValueSet
    attributes: {id: ADC_CTRLB_PRESCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: ADC_EVCTRL_FLUSH}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: ADC_EVCTRL_START}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: ADC_INPUTCTRL_MUXPOS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Boolean
    attributes: {id: ADC_INTENSET_RESRDY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: ADC_SAMPCTRL_SAMPLEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
  - type: Comment
    attributes: {id: ADC_SAMPCTRL_SAMPLEN_TIME}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Conversion Time is 1.33333333333 uS ****'}
  - type: Menu
    attributes: {id: ADC_SEQUENCE_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '295', y: '79', id: adc0}
