format_version: v1.0
type: UniqueComponent
attributes: {id: divas}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DIVAS_DIV_OVERLOAD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '13', y: '139', id: divas}
