format_version: v1.0
type: UniqueComponent
attributes: {id: pmsm_foc}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: MCPMSMFOC_ADCPLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: adc0}
  - type: String
    attributes: {id: MCPMSMFOC_ADCPLIB1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: adc1}
  - type: Boolean
    attributes: {id: MCPMSMFOC_ADC_BOARD_DEP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: 'false'}
  - type: Integer
    attributes: {id: MCPMSMFOC_ADC_DEP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '1'}
  - type: Integer
    attributes: {id: MCPMSMFOC_ADC_MAX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '4095'}
  - type: Float
    attributes: {id: MCPMSMFOC_BEMF_CONST}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '44.38'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_BOARD_SEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_CONTROL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: MCPMSMFOC_DCBUSV_CH}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '27'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '9'}
  - type: Integer
    attributes: {id: MCPMSMFOC_DCBUSV_MODULE}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '1'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0'}
  - type: Float
    attributes: {id: MCPMSMFOC_DC_BUS_RATIO}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.0076601673'}
  - type: Float
    attributes: {id: MCPMSMFOC_DC_BUS_RBOTTOM}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2.2'}
  - type: Float
    attributes: {id: MCPMSMFOC_DC_BUS_RTOP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '285.0'}
  - type: Float
    attributes: {id: MCPMSMFOC_DC_BUS_VOLT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '400.0'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_DIRECTION_BUTTON}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '51'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_DIRECTION_LED}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '42'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_FAULT_LED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '43'}
  - type: Float
    attributes: {id: MCPMSMFOC_ID_KI}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '469.0'}
  - type: Float
    attributes: {id: MCPMSMFOC_ID_KP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '6.1'}
  - type: Float
    attributes: {id: MCPMSMFOC_IQ_KI}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '469.0'}
  - type: Float
    attributes: {id: MCPMSMFOC_IQ_KP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '6.1'}
  - type: Float
    attributes: {id: MCPMSMFOC_IU_OPAMP_GAIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '10.06'}
  - type: Float
    attributes: {id: MCPMSMFOC_IU_OPAMP_OFFSET}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '1.65'}
  - type: Float
    attributes: {id: MCPMSMFOC_IU_OPAMP_SHUNT_R}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.01'}
  - type: Float
    attributes: {id: MCPMSMFOC_IV_OPAMP_GAIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '10.06'}
  - type: Float
    attributes: {id: MCPMSMFOC_IV_OPAMP_OFFSET}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '1.65'}
  - type: Float
    attributes: {id: MCPMSMFOC_IV_OPAMP_SHUNT_R}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.01'}
  - type: Float
    attributes: {id: MCPMSMFOC_LD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.00253'}
  - type: Float
    attributes: {id: MCPMSMFOC_LQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.00253'}
  - type: Float
    attributes: {id: MCPMSMFOC_MAX_CURRENT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '16.40159'}
  - type: Float
    attributes: {id: MCPMSMFOC_MAX_MOTOR_CURRENT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '4.0'}
  - type: Float
    attributes: {id: MCPMSMFOC_MAX_SPEED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '5000.0'}
  - type: Float
    attributes: {id: MCPMSMFOC_MAX_TORQUE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Float
    attributes: {id: MCPMSMFOC_MIN_TORQUE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_MOTOR_CONNECTION}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_MOTOR_SEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PHASEU_CH}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '27'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PHASEU_MODULE}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '1'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PHASEV_CH}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '27'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '5'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PHASEV_MODULE}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '1'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '1'}
  - type: Float
    attributes: {id: MCPMSMFOC_PLL_ED_FILTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.122'}
  - type: Float
    attributes: {id: MCPMSMFOC_PLL_EQ_FILTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.122'}
  - type: Float
    attributes: {id: MCPMSMFOC_PLL_SPEED_FILTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.122'}
  - type: Float
    attributes: {id: MCPMSMFOC_POLE_PAIRS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '5.0'}
  - type: Integer
    attributes: {id: MCPMSMFOC_POT_CH}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '27'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0'}
  - type: Integer
    attributes: {id: MCPMSMFOC_POT_MODULE}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '1'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '1'}
  - type: String
    attributes: {id: MCPMSMFOC_PWMPLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: tcc0}
  - type: Boolean
    attributes: {id: MCPMSMFOC_PWM_BOARD_DEP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: 'false'}
  - type: Float
    attributes: {id: MCPMSMFOC_PWM_DEAD_TIME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2.0'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_PWM_FAULT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PWM_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '10000'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PWM_PH_U}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '3'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PWM_PH_V}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '3'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '1'}
  - type: Integer
    attributes: {id: MCPMSMFOC_PWM_PH_W}
    children:
    - type: Attributes
      children:
      - type: Integer
        attributes: {id: max}
        children:
        - {type: Value, value: '3'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2'}
  - type: Integer
    attributes: {id: MCPMSMFOC_QE_PULSES_PER_REV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '2500'}
  - type: Float
    attributes: {id: MCPMSMFOC_R}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '1.39'}
  - type: Float
    attributes: {id: MCPMSMFOC_RATED_SPEED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '3000.0'}
  - type: Float
    attributes: {id: MCPMSMFOC_SPEED_KI}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: 'Ki (* 0.01) '}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.03'}
  - type: Float
    attributes: {id: MCPMSMFOC_SPEED_KP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '0.001'}
  - type: KeyValueSet
    attributes: {id: MCPMSMFOC_START_BUTTON}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: '11'}
  - type: String
    attributes: {id: MCPMSMFOC_X2CScope}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pmsm_foc, value: X2CScope}
- type: Attachments
  children:
  - type: MultiCapability
    attributes: {id: pmsmfoc_ADC}
    children:
    - type: TargetAttachments
      children:
      - type: TargetAttachment
        attributes: {targetComponentID: adc1, targetAttachmentID: ADC1_ADC}
      - type: TargetAttachment
        attributes: {targetComponentID: adc0, targetAttachmentID: ADC0_ADC}
  - type: DirectDependency
    attributes: {id: pmsmfoc_PWM}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: tcc0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: TCC0_PWM}
  - type: DirectDependency
    attributes: {id: pmsmfoc_X2CSCOPE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: X2CScope}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: x2cScope_Scope}
- type: ElementPosition
  attributes: {x: '283', y: '227', id: pmsm_foc}
