format_version: v1.0
type: UniqueComponent
attributes: {id: tcc1}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: INTR_PWM_FAULT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc1, value: TCC1_OTHER_IRQn}
  - type: String
    attributes: {id: PWM_CALLBACK_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc1, value: TCC1_PWMCallbackRegister}
  - type: String
    attributes: {id: PWM_GET_PERIOD_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc1, value: TCC1_PWM24bitPeriodGet}
  - type: String
    attributes: {id: PWM_OUTPUT_DISABLE_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc1, value: TCC1_PWMPatternSet}
  - type: String
    attributes: {id: PWM_OUTPUT_ENABLE_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc1, value: TCC1_PWMPatternSet}
  - type: Hex
    attributes: {id: PWM_PATTERN_MASK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc1, value: '119'}
  - type: Hex
    attributes: {id: PWM_PH_MASK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc1, value: '7'}
  - type: String
    attributes: {id: PWM_PH_U}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc1, value: TCC1CHANNEL0}
  - type: String
    attributes: {id: PWM_PH_V}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc1, value: TCC1CHANNEL1}
  - type: String
    attributes: {id: PWM_PH_W}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc1, value: TCC1CHANNEL2}
  - type: String
    attributes: {id: PWM_SET_DUTY_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc1, value: TCC1_PWM24bitDutySet}
  - type: String
    attributes: {id: PWM_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc1, value: TCC1_PWMStart}
  - type: String
    attributes: {id: PWM_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcc1, value: TCC1_PWMStop}
  - type: Integer
    attributes: {id: TCC_0_CC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1000'}
  - type: KeyValueSet
    attributes: {id: TCC_0_WAVE_POL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: TCC_0_WAVE_POL_NPWM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: TCC_1_CC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2000'}
  - type: KeyValueSet
    attributes: {id: TCC_1_WAVE_POL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: TCC_1_WAVE_POL_NPWM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: TCC_CTRLBSET_DIR}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: TCC_EVCTRL_EVACT0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: Boolean
    attributes: {id: TCC_EVCTRL_MCEO_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TCC_EVCTRL_MCEO_1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TCC_EVCTRL_TCINV0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: TCC_FREQUENCY}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** PWM Frequency is 4000 Hz ****'}
  - type: Boolean
    attributes: {id: TCC_INTENSET_OVF}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: TCC_PER_PER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6000'}
  - type: KeyValueSet
    attributes: {id: TCC_WAVE_WAVEGEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '432', y: '157', id: tcc1}
