format_version: v1.0
type: UniqueComponent
attributes: {id: X2CScope}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: X2C_SCOPE_PERIPH_USED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: SERCOM3_USART}
  - type: String
    attributes: {id: X2C_SCOPE_UART_BAUD_RATE_SYMBOL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: USART_BAUD_RATE}
  - type: String
    attributes: {id: X2C_SCOPE_UART_ID}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: sercom3}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: x2cScopeUartDependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sercom3}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SERCOM3_UART}
  - type: DirectCapability
    attributes: {id: x2cScope_Scope}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: pmsm_foc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: pmsmfoc_X2CSCOPE}
- type: ElementPosition
  attributes: {x: '166', y: '396', id: X2CScope}
