format_version: v1.0
type: UniqueComponent
attributes: {id: tc4}
children:
- type: Symbols
  children:
  - type: Comment
    attributes: {id: TC_COMPARE_PERIOD_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** Compare Period is 3.0 us ****'}
  - type: Integer
    attributes: {id: TC_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc4, value: '8000000'}
  - type: Comment
    attributes: {id: TC_Resolution}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '****Timer resolution is 125.0 nS****'}
  - type: Long
    attributes: {id: TC_TIMER_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc4, value: '8000'}
  - type: Float
    attributes: {id: TC_TIMER_TIME_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '8.191875'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1.0'}
- type: ElementPosition
  attributes: {x: '289', y: '294', id: tc4}
